version: '3.8'

services:
  netplan-web-generator:
    build: 
      context: .
      dockerfile: Dockerfile
    image: netplan-web-generator:latest
    container_name: netplan-web-generator
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netplan-web.rule=Host(`netplan.localhost`)"
      - "traefik.http.services.netplan-web.loadbalancer.server.port=8080"
      - "maintainer=Michael Tinsay"
      - "version=1.0.0"
      - "license=GPLv3"
    networks:
      - netplan-network

networks:
  netplan-network:
    driver: bridge
    labels:
      - "description=Network for Netplan Web Generator"